title: "Hybrid CCTV Galle"
tagline: "Top CCTV provider in Galle, Hikvision, Dahua, CCTV shop"
email: contact@uslayer.com
formspree: xqknzwyk
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/hybrid-cctv-logo.svg'
favicon: 'assets/images/fav.svg'
author: Hybrid CCTV Galle
paginate: 30
disqus: 'us-layer'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true


ganalytics: G-KZX7D46K93
fbpageid: HybridCCTVGalle


# Social
social:
#  instagram: https://www.instagram.com/uslayer/
  facebook: https://www.facebook.com/HybridCCTVGalle
  twitter: https://twitter.com/us_layer
  youtube: https://www.youtube.com/uslayer

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
